#!/usr/bin/env node
/**
 * Writes dist/sw.js with a precache list of whatever the build just produced.
 * Runs automatically after `npm run build`.
 *
 * The service worker exists so the app opens on a phone with no signal - your
 * guesses and already-revealed lines are local anyway. It never touches
 * api.the-odds-api.com: odds are not something to serve stale.
 */
import { createHash } from 'node:crypto'
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join, relative, resolve } from 'node:path'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const DIST = resolve(ROOT, 'dist')

const walk = (dir) => readdirSync(dir).flatMap((entry) => {
  const full = join(dir, entry)
  return statSync(full).isDirectory() ? walk(full) : [full]
})

const files = walk(DIST)
  .map((f) => `./${relative(DIST, f).split(/[\\/]/).join('/')}`)
  .filter((f) => !f.endsWith('/sw.js') && !f.endsWith('.map'))
  .sort()

// Version the cache by the content of everything in it, so a rebuild that
// changes nothing does not needlessly evict a working cache.
const hash = createHash('sha256')
for (const f of files) hash.update(readFileSync(join(DIST, f.slice(2))))
const version = hash.digest('hex').slice(0, 12)

const sw = `// Generated by scripts/build-sw.mjs - do not edit.
const VERSION = ${JSON.stringify(version)}
const CACHE = \`guessing-lines-\${VERSION}\`
const ASSETS = ${JSON.stringify(files, null, 2)}
const INDEX = './index.html'

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE)
      .then((cache) => cache.addAll(ASSETS))
      .then(() => self.skipWaiting()),
  )
})

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys()
    await Promise.all(
      keys.filter((k) => k.startsWith('guessing-lines-') && k !== CACHE).map((k) => caches.delete(k)),
    )
    await self.clients.claim()
  })())
})

self.addEventListener('fetch', (event) => {
  const request = event.request
  if (request.method !== 'GET') return
  const url = new URL(request.url)
  // Anything off-origin - The Odds API above all - goes straight to the network.
  if (url.origin !== self.location.origin) return

  // Navigations: fresh if we can reach the network, the cached shell if not.
  if (request.mode === 'navigate') {
    event.respondWith((async () => {
      try {
        return await fetch(request)
      } catch {
        const cache = await caches.open(CACHE)
        return (await cache.match(INDEX)) || Response.error()
      }
    })())
    return
  }

  // Build output is content-hashed, so a cache hit is always the right answer.
  event.respondWith((async () => {
    const cache = await caches.open(CACHE)
    const hit = await cache.match(request, { ignoreSearch: false })
    if (hit) return hit
    try {
      const response = await fetch(request)
      if (response.ok && response.type === 'basic') cache.put(request, response.clone())
      return response
    } catch {
      return Response.error()
    }
  })())
})
`

writeFileSync(join(DIST, 'sw.js'), sw)
console.log(`dist/sw.js  ${files.length} files precached  version ${version}`)
